export const T = {
    bg: "var(--bg)",
    surface: "var(--surface)",
    card: "var(--card)",
    cardHover: "var(--card-hover)",
    border: "var(--border)",
    borderHi: "var(--border-hi)",
    accent: "var(--accent)",
    accentDim: "var(--accent-dim)",
    accentMid: "var(--accent-mid)",
    warn: "var(--warn)",
    warnDim: "var(--warn-dim)",
    danger: "var(--danger)",
    dangerDim: "var(--danger-dim)",
    blue: "var(--blue)",
    blueDim: "var(--blue-dim)",
    text: "var(--text)",
    textSoft: "var(--text-soft)",
    textDim: "var(--text-dim)",
    mono: "var(--font-mono)",
    sans: "var(--font-sans)",
    body: "var(--font-body)",
};
